import type { Metadata } from "next"
import { Inter } from "next/font/google"
import "./globals.css"
import { Toaster } from "react-hot-toast"
import ConvexClientProvider from "@/providers/ConvexClientProvider"
import Navbar from "@/components/Navbar"
import { AuthProvider } from "@/providers/AuthProvider"
const inter = Inter({ subsets: ["latin"] })

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {/* <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        > */}
              <ConvexClientProvider>
                   <AuthProvider>
                <Navbar></Navbar>
                {children}
                </AuthProvider>
                </ConvexClientProvider>
     
            <Toaster />
          {/* </ConvexClientProvider> */}
        {/* </ThemeProvider> */}
      </body>
    </html>
  )
}
